### PR TITLE
Fix android nougat display spinner

### LINKED ISSUE #117: DatePicker on spinner mode not working on some Phones
# Bug

I'm trying to use the datepicker on spinner mode with Expo, but on some devices, it shows the calendar mode.

I tested on an emulator with Android SDK 24 and the problem occurs.

On SDK 26 and 29 the datepicker worked on the emulators. However, After I build the app with expo, it doesn't work on any phone.

I created a repo here:

https://github.com/otaviogaiao/teste-datepicker

The problem is basically the same one stated here: https://github.com/react-native-community/react-native-datetimepicker/issues/76

## Environment info

Expo SDK 36
react-native-datepicker 2.2.2

### PR DESCRIPTION
**Pull request by luancurti**
# Summary

Display spinner should respect `display prop`

Closes #117 

## Test Plan

Run this `demo` https://github.com/otaviogaiao/teste-datepicker and `date picker` with mode `spinner` and date picker with spinner should be displayed

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| Android |    ✅❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

File: android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java [hunk 1]
```diff
@@ -62,24 +64,20 @@ protected void onStop() {
...
         final TypedArray a =
             context.obtainStyledAttributes(
                 null, datePickerStyleable, android.R.attr.datePickerStyle, 0);
-        Field datePickerModeStyleableField = styleableClass.getField("DatePicker_datePickerMode");
-        int datePickerModeStyleable = datePickerModeStyleableField.getInt(null);
-        final int mode = a.getInt(datePickerModeStyleable, MODE_SPINNER);
         a.recycle();
 
-        if (mode == MODE_SPINNER) {
+        if (display == RNDatePickerDisplay.SPINNER) {
```
Comment (vonovak) [inline android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: @luancurti why does the previous solution not work here? Thanks.

Comment (lochness42) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: That's good question

Comment (luancurti) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: In some cases according the theme o datetime picker the mode is `1` or `2` see this gist https://gist.github.com/jeffdgr8/6bc5f990bf0c13a7334ce385d482af9f#file-timepickerdialogfixednougatspinner-java-L68 and this comments https://gist.github.com/jeffdgr8/6bc5f990bf0c13a7334ce385d482af9f#gistcomment-1888988
https://gist.github.com/jeffdgr8/6bc5f990bf0c13a7334ce385d482af9f#gistcomment-1911283
because this I changed this logic and after some tests on android `7.0` when passing `display = calendar` the picker `always` show `spinner` to `respect the display` I change this comparison to only show this property. What do you think?

Comment (lochness42) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: Alright that makes sense to me

**Comment by vonovak** [comment]
Let me please take a look at this before we merge, thanks!

**Comment by luancurti** [comment]
> Let me please take a look at this before we merge, thanks!

Of Course!

**Comment by lochness42** [comment]
That's why I didn't merge it yet

File: android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java (hunk 1 above)
Comment (vonovak) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: @luancurti previously, `fixSpinner` was called from 

**TimePicker**

https://github.com/react-native-community/react-native-datetimepicker/blob/e6d2980230b1e27fa8aed989ccbb79897e6ef5eb/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java#L43

and **DatePicker**

https://github.com/react-native-community/react-native-datetimepicker/blob/e6d2980230b1e27fa8aed989ccbb79897e6ef5eb/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java#L42

with your change, because of `if (display == RNDatePickerDisplay.SPINNER)`, it will only be executed for `DatePicker` and not for `TimePicker` because for `TimePicker` there is `RNTimePickerDisplay.SPINNER`, and  `RNTimePickerDisplay.SPINNER != RNDatePickerDisplay.SPINNER`. Is this change intended? 

Is the bug only present on `DatePicker` or is it present on both `DatePicker` and `TimePicker`? Thanks!

Comment (luancurti) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: @vonovak I'll investigate on `TimePicker`, now I don't know 😕

Comment (luancurti) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: @vonovak apparently `TimePicker` has the same `issue` https://github.com/react-native-community/react-native-datetimepicker/blob/d60bff69c54f0180d3373367d5efbd8c2f455744/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableTimePickerDialog.java#L75 but I have an idea to control when show `TimePicker`  we can add a `isVisible` (in `DatePicker` case we should check `display` property is equal `RNDatePickerDisplay.SPINNER`) property to control when the `DatePicker` or `TimePicker` should show and remove this `if` checking `mode === MODE_SPINNER`. What do you think?

Comment (vonovak) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: firstly, in my previous comment I commented on `fixSpinner` being called from `TimePicker` and `DatePicker`, and I thought they were the same functions, but they are not.

You already fixed the `fixSpinner` method in `RNDismissableDatePickerDialog.java`, which means we can add the same logic also to `RNDismissableTimePickerDialog.java` - correct?

> we can add a `isVisible`

sorry, I don't understand what you mean by that / why that is needed.

> remove this if checking mode === MODE_SPINNER 

yes, that check is not needed and this check https://github.com/react-native-community/react-native-datetimepicker/blob/385c9ebf7bd948538e14a92831ec352c0fd87cff/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java#L80

can be moved up into `if (Build.VERSION.SDK_INT == Build.VERSION_CODES.N)...`

lastly, we should check that switching display from `SPINNER` to some to some other type is correctly reflected by the module, because some of it's state appears to be reused (see https://github.com/react-native-community/react-native-datetimepicker/blob/385c9ebf7bd948538e14a92831ec352c0fd87cff/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java#L103). Hope you understand what I mean :)

Comment (luancurti) [reply android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java]: Sorry for the delay

> firstly, in my previous comment I commented on `fixSpinner` being called from `TimePicker` and `DatePicker`, and I thought they were the same functions, but they are not.
> 
> You already fixed the `fixSpinner` method in `RNDismissableDatePickerDialog.java`, which means we can add the same logic also to `RNDismissableTimePickerDialog.java` - correct?
> 

I believe so

> 
> sorry, I don't understand what you mean by that / why that is needed.
> 
> > remove this if checking mode === MODE_SPINNER
> 
> yes, that check is not needed and this check
> 
> https://github.com/react-native-community/react-native-datetimepicker/blob/385c9ebf7bd948538e14a92831ec352c0fd87cff/android/src/main/java/com/reactcommunity/rndatetimepicker/RNDismissableDatePickerDialog.java#L80
> 
> can be moved up into `if (Build.VERSION.SDK_INT == Build.VERSION_CODES.N)...`
> 

Sure!

> lastly, we should check that switching display from `SPINNER` to some to some other type is correctly reflected by the module, because some of its state appears to be reused (see
> 
> https://github.com/react-native-community/react-native-datetimepicker/blob/385c9ebf7bd948538e14a92831ec352c0fd87cff/android/src/main/java/com/reactcommunity/rndatetimepicker/RNTimePickerDialogModule.java#L103
> 
I'll check this. Thanks for detailed explanation!

**Comment by TreeMan360** [comment]
Any idea when this will be merged in?

**Comment by TreeMan360** [comment]
I thought this was going to make it into SDK 37 ;(

**Comment by vonovak** [comment]
@luancurti are you planning to look into this? Thanks :)

**Comment by luancurti** [comment]
> @luancurti are you planning to look into this? Thanks :)

Yes, I'll make the suggested changes before the weekend

**Comment by luancurti** [comment]
Tested on `Android Nougat 7.0 SDK 24`

datetimepicker

**Comment by TreeMan360** [comment]
This does not fix the problem for me once deployed as a standalone app (expo). I still get the 'default' clock when I select 'spinner'.

**Comment by vonovak** [comment]
@TreeMan360 as you pointed out, this fix is not available in expo 37 (managed workflow), so I'm unsure how you're reproducing it. Please open a new issue and provide a runnable reproduction, or alternatively, consider contributing a PR with a fix for your issue, thank you.

**Comment by TreeMan360** [comment]
> @TreeMan360 as you pointed out, this fix is not available in expo 37 (managed workflow), so I'm unsure how you're reproducing it. Please open a new issue and provide a runnable reproduction (follow the issue template), or alternatively, consider contributing a PR with a fix for your issue, thank you.

I just referenced the new library and ignored the expo warning saying it may not be compatible. I assume from your response that this is not plausible so I guess I will either be forced to not use this library or wait until 38 (far from ideal).

**Comment by vonovak** [comment]
Expo sdk ships native code from one of the previous versions of this package (use expo install to find which one), so even if you manually install the latest version of this package you will not actually run the latest version.

But note that the bug which was fixed on this PR only exists in Android version 7, and it's not a bug that would prevent user from picking a date.

**Comment by TreeMan360** [comment]
Ok thanks for the explanation that makes sense. My problem is simply that once I make a standalone app the “spinner” display is not used. This is across multiple android versions, I always get the clock. It’s fine in development. So is this a separate issue?

**Comment by vonovak** [comment]
This sounds like a separate issue. But if it's fine in development but wrong in release build, that's pretty weird. You can try opening a new issue but please note we require runnable reproduction to consider the issue as valid - and that might not be easy in this case. 
It might be best if you investigate this yourself because I think it'll take a while before maintenainers will have time to look into this.
